# Generated by Django 5.0.6 on 2024-06-13 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Anotacoes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='date_added',
            new_name='date',
        ),
    ]
