# Generated by Django 5.0.6 on 2024-06-17 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Anotacoes', '0004_task_important'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
